version: 0.1.0.{build}

environment:
  packageVersion: 0.1.0
  release: true

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: >-
    if ($env:release -eq $true) { 
      $env:nugetVersion = $env:packageVersion 
    } else {
      $env:nugetVersion = "$env:packageVersion-beta-$env:appveyor_build_number"
    }
- ps: Update-AppveyorBuild -Version $env:buildVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

configuration: Release

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

before_build:
- nuget restore

build:
  verbosity: minimal

after_build:
- ps: nuget pack Odin-Commands.nuspec -version "$env:nugetVersion"

artifacts:
- path: 'Odin-Commands*.nupkg'
  name: odin-nuget-package

deploy:
- provider: NuGet
  api_key:
    secure: oZLUyd94wnic5VlRfHZnlopK4I2tNOT30JMOp0nWrH/i+ZOyVYKayPbfy407OZdL
  artifact: odin-nuget-package
  on:
    branch: master